doorList =
{
    {
        location = 'Rockford PD',
        centralPos = vector3(-566.45, -115.86, 33.88),
        distanceCheck = 60,  -- Distance used to grab all the doors in the area. MUST be large enough to cover all the doors for that building/area
        groupInfo = {
             owners = {'XCS85530'}, -- List of people who can manage access via commands
             storageLocations = { -- List of locations with storage points (inside of area)
                 vector3(-622.2329, -230.0031, 38.05707)
             },
             wardrobeLocations = { -- List of locations with wardrobe points (inside of area)
                 vector3(-631.0296, -228.2591, 38.05706)
             }
        },
        doors =
        {
            {
                name = 'Front Double',  -- Just used to identify the door
                jobs = {'police'},
                doorModel = -1320876379,
                doubleDoor = true,
                doorPos = {[1] = vector3(-557.36, -124.63, 38.03), [2] = vector3(-558.38, -122.23, 38.03)},
                textPos = vector3(-557.75, -123.44, 37.88),
                heading1 = 293.19,  -- When closed
                heading2 = 113.19,
                isLocked = false,  -- Default lock status
                unlockDistance = 2.0,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = true,  -- Whether the door can be lockpicked
                autoLock = true,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
            {
                name = 'Front Main Gate to Cells',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-561.22, -115.81, 34.02),
                textPos = vector3(-561.67, -114.87, 33.87),
                heading = 293.63,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 1',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-562.30, -120.32, 34.02),
                textPos = vector3(-562.73, -119.39, 33.87),
                heading = 293.21,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 2',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-564.66, -121.34, 34.02),
                textPos = vector3(-565.01, -120.36, 33.87),
                heading = 293.19,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Exit Gate to Garage',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-575.99, -122.13, 34.02),
                textPos = vector3(-576.48, -121.07, 33.88),
                heading = 293.21,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Grey Double',
                jobs = {'police'},
                doorModel = 452874391,
                doubleDoor = true,
                doorPos = {[1] = vector3(-565.30, -106.05, 34.02), [2] = vector3(-566.33, -103.65, 34.02)},
                textPos = vector3(-565.46, -104.72, 33.88),
                heading1 = 293.00,
                heading2 = 113.00,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Grey Double2',
                jobs = {'police'},
                doorModel = 452874391,
                doubleDoor = true,
                doorPos = {[1] = vector3(-570.61, -117.18, 34.02), [2] = vector3(-573.00, -118.21, 34.02)},
                textPos = vector3(-571.82, -117.51, 33.88),
                heading1 = 23.19,
                heading2 = 203.19,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Brown Double',
                jobs = {'police'},
                doorModel = -543497392,
                doubleDoor = true,
                doorPos = {[1] = vector3(-542.79, -105.51, 34.00), [2] = vector3(-515.11, -106.45, 34.00)},
                textPos = vector3(-571.82, -117.51, 33.88),
                heading1 = 23.19,
                heading2 = 203.19,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Grey Double3 - Evidence',
                jobs = {'police'},
                doorModel = 452874391,
                doubleDoor = true,
                doorPos = {[1] = vector3(-547.31, -102.50, 34.01), [2] = vector3(-548.33, -100.10, 34.01)},
                textPos = vector3(-547.78, -101.20, 33.86),
                heading1 = 293.19,
                heading2 = 113.19,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },                                                            
            -- {
            --     name = 'Main Cell Gate',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(464.57, -992.66, 25.06),
            --     textPos = vector3(463.94, -992.47, 24.92),
            --     heading = 359.78,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },   
            -- {
            --     name = 'Cell 1',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(462.30, -993.60, 24.90),
            --     textPos = vector3(461.80, -993.30, 25.00),
            --     heading = 269.59,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- }, 
            -- {
            --     name = 'Cell 2',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(462.30, -998.10, 24.90),
            --     textPos = vector3(461.80, -998.80, 25.00),
            --     heading = 90.00,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },
            -- {
            --     name = 'Cell 3',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(462.70, -1001.90, 24.90),
            --     textPos = vector3(461.80, -1002.40, 25.00),
            --     heading = 90.00,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },
            -- {
            --     name = 'Cell 4',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(465.92, -997.63, 25.06),
            --     textPos = vector3(466.01, -998.70, 25.00),
            --     heading = 90.00,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- }, 
            -- {
            --     name = 'Cell 5',
            --     jobs = {'police'},
            --     doorModel = 631614199,
            --     doubleDoor = false,
            --     doorPos = vector3(465.91, -1001.33, 25.06),
            --     textPos = vector3(465.99, -1002.34, 25.00),
            --     heading = 90.00,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 5,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },
            -- {
            --     name = 'Double Doors Rear',
            --     jobs = {'police'},
            --     doorModel = -2023754432,
            --     doubleDoor = true,
            --     doorPos = {[1] = vector3(467.37, -1014.45, 26.53), [2] = vector3(469.96, -1014.45, 26.53)},
            --     textPos = vector3(468.60, -1014.40, 26.50),
            --     heading1 = 0.0,
            --     heading2 = 180.0,
            --     isLocked = true,
            --     unlockDistance = 3.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 120,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },                                                                                 
            -- {
            --     name = 'Rear Gate',
            --     jobs = {'police'},
            --     doorModel = -1603817716,
            --     doorPos = vector3(488.89480, -1017.2100, 27.14651),
            --     textPos = vector3(488.89480, -1020.2100, 29.0),
            --     heading = 90.0,
            --     isLocked = true,
            --     isGate = true,
            --     unlockDistance = 13.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = false,
            --     autoLockTimer = 120,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- }
        }
    },
    {
        location = 'MRPD',  
        centralPos = vector3(449.27, -984.73, 30.69),  
        distanceCheck = 60,  -- Distance used to grab all the doors in the area. MUST be large enough to cover all the doors for that building/area
        doors =
        {
            {
                name = 'Side Double1',
                jobs = {'police'},
                multiModel = true,
                doubleDoor = true,
                doorModel = {[1] = 1388858739, [2] = -165604314},
                doorPos = {[1] = vector3(439.2086, -998.68, 30.79), [2] = vector3(441.24, -998.68, 30.79)},
                textPos = vector3(440.15, -998.81, 30.72),
                heading1 = 180.00,
                heading2 = 180.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 90,
                autoLockCooldown = 0,
                lockAtNight = false
            },              
            {
                name = 'Side Double2',
                jobs = {'police'},
                multiModel = true,
                doubleDoor = true,
                doorModel = {[1] = 1388858739, [2] = -165604314},
                doorPos = {[1] = vector3(441.59, -998.68, 30.79), [2] = vector3(443.83, -998.68, 30.79)},
                textPos = vector3(442.74, -998.83, 30.72),
                heading1 = 179.87,
                heading2 = 179.79,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 90,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cam Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1543859032,
                doorPos = vector3(437.72, -995.33, 30.82),
                textPos = vector3(438.81, -995.38, 30.69),
                heading = 0.13,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'MetalDetect',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(441.76, -994.27, 30.81),
                textPos = vector3(440.62, -994.34, 30.69),
                heading = 180.27,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Evidence Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1543859032,
                doorPos = vector3(472.21, -1002.59, 34.34),
                textPos = vector3(471.10, -1002.53, 34.22),
                heading = 180.23,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Stairs Access 3rd Floor',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(468.17, -991.84, 30.82),
                textPos = vector3(467.09, -991.93, 30.69),
                heading = 180.26,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Stairs Access 2rd Floor',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(468.17, -991.79, 34.34),
                textPos = vector3(467.06, -991.58, 34.22),
                heading = 179.98,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Stairs Access 1st Floor',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(468.17, -991.85, 25.85),
                textPos = vector3(467.17, -991.83, 25.73),
                heading = 180.07,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Garage Access',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(464.87, -989.32, 25.86),
                textPos = vector3(464.86, -988.32, 25.73),
                heading = 90.0,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Armory',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1543859032,
                doorPos = vector3(487.55, -997.31, 25.85),
                textPos = vector3(486.49, -997.35, 25.73),
                heading = 179.87,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },                                                
            {
                name = 'Cell 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1988553564,
                doorPos = vector3(462.14, -989.14, 34.33),
                textPos = vector3(461.04, -989.07, 34.22),
                heading = 0.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1988553564,
                doorPos = vector3(456.22, -989.14, 34.33),
                textPos = vector3(455.06, -989.07, 34.22),
                heading = 0.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 3',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1988553564,
                doorPos = vector3(450.28, -989.14, 34.33),
                textPos = vector3(449.17, -989.06, 34.22),
                heading = 0.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 4',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -884718443,
                doorPos = vector3(448.99, -984.66, 34.34),
                textPos = vector3(450.18, -984.77, 34.22),
                heading = 180.09,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 5',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -884718443,
                doorPos = vector3(454.91, -984.66, 34.34),
                textPos = vector3(456.06, -984.81, 34.22),
                heading = 180.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell 6',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1988553564,
                doorPos = vector3(460.84, -984.66, 34.34),
                textPos = vector3(462.00, -984.77, 34.22),
                heading = 180.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'To Interview Rooms',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(445.34, -986.30, 34.31),
                textPos = vector3(445.32, -987.51, 34.20),
                heading = 270.03,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Viewing 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(441.35, -991.08, 34.31),
                textPos = vector3(441.34, -989.97, 34.20),
                heading = 90.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Interview 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1543859032,
                doorPos = vector3(441.35, -995.25, 34.31),
                textPos = vector3(441.30, -994.16, 34.20),
                heading = 90.14,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Viewing 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 165994623,
                doorPos = vector3(439.89, -984.85, 34.31),
                textPos = vector3(440.96, -984.88, 34.20),
                heading = 0.00,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Interview 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1543859032,
                doorPos = vector3(435.78, -984.85, 34.32),
                textPos = vector3(436.83, -984.84, 34.20),
                heading = 0.34,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Roof Access',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -340230128,
                doorPos = vector3(464.27, -983.37, 43.83),
                textPos = vector3(464.30, -984.51, 43.69),
                heading = 269.88,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },                                                                                                                                                                                              
            {
                name = 'Double Doors Rear',
                jobs = {'police'},
                doorModel = -2023754432,
                doubleDoor = true,
                doorPos = {[1] = vector3(467.37, -1014.45, 26.53), [2] = vector3(469.96, -1014.45, 26.53)},
                textPos = vector3(468.60, -1014.40, 26.50),
                heading1 = 0.0,
                heading2 = 180.0,
                isLocked = true,
                unlockDistance = 3.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 120,
                autoLockCooldown = 0,
                lockAtNight = false
            },                                                                                 
            {
                name = 'Rear Gate',
                jobs = {'police'},
                doorModel = -1603817716,
                doorPos = vector3(488.89480, -1017.2100, 27.14651),
                textPos = vector3(488.89480, -1020.2100, 29.0),
                heading = 90.0,
                isLocked = true,
                isGate = true,
                unlockDistance = 13.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 120,
                autoLockCooldown = 0,
                lockAtNight = false
            }
        }
    },    
    {
        location = 'Vangelico',
        centralPos = vector3(-623.09, -232.03, 38.06),
        distanceCheck = 15,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'FrontDoors',
                jobs = {'police', 'ambulance'},
                multiModel = true,
                doubleDoor = true,
                doorModel = {[1] = 1425919976, [2] = 9467943},
                doorPos = {[1] = vector3(-631.95, -236.33, 38.20), [2] = vector3(-630.42, -238.43, 38.20)},
                textPos = vector3(-631.17, -237.34, 38.08),
                heading1 = 305.91,
                heading2 = 306.08,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = true,
                autoLock = true,
                relock = false,
                autoLockTimer = 90,
                autoLockCooldown = 0,
                lockAtNight = false
            }
        }
    },
    {
        location = 'FIB Ground Floor',
        centralPos = vector3(132.66, -762.75, 45.74),
        distanceCheck = 50,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'FrontDoors',
                jobs = {'police', 'ambulance'},
                multiModel = true,
                doubleDoor = true,
                doorModel = {[1] = -1517873911, [2] = -90456267},
                doorPos = {[1] = vector3(106.37, -742.69, 46.18), [2] = vector3(105.76, -746.64, 46.18)},
                textPos = vector3(105.93, -744.66, 45.75),
                heading1 = 78.21,
                heading2 = 84.05,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = true,
                autoLock = true,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },         
        }
    },
    {
        location = 'FIB 47th Floor',
        centralPos = vector3(117.95, -752.39, 234.15),
        distanceCheck = 50,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'Single Security Door 47th Floor',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1821777087,
                doorPos = vector3(124.02, -727.31, 234.30),
                textPos = vector3(123.38, -729.02, 234.35),
                heading = 70.04,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = true,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },            
        }
    },
    {
        location = 'Sandy PD',
        centralPos = vector3(1851.61, 3691.40, 34.27),
        distanceCheck = 15,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'To Breifing Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -2023754432,
                doorPos = vector3(1857.25, 3690.29, 34.41),
                textPos = vector3(1856.38, 3689.72, 34.27),
                heading = 209.41,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Captains Office',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1765048490,
                doorPos = vector3(1860.74, 3692.40, 34.59),
                textPos = vector3(1859.86, 3691.83, 34.27),
                heading = 30.14,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Evidence Locker',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1526539404,
                doorPos = vector3(1858.15, 3699.13, 34.54),
                textPos = vector3(1857.20, 3698.47, 34.27),
                heading = 209.70,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Double Doors To Armory',
                jobs = {'police'},
                doorModel = -2023754432,
                doubleDoor = true,
                doorPos = {[1] = vector3(1847.13, 3689.94, 34.41), [2] = vector3(1849.40, 3691.20, 34.41)},
                textPos = vector3(1848.34, 3690.52, 34.27),
                heading1 = 28.68,
                heading2 = 208.96,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 120,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Double Doors To Cells',
                jobs = {'police'},
                doorModel = -2023754432,
                doubleDoor = true,
                doorPos = {[1] = vector3(1851.28, 3681.87, 34.41), [2] = vector3(1849.98, 3684.11, 34.41)},
                textPos = vector3(1850.61, 3682.97, 34.27),
                heading1 = 120.31,
                heading2 = 299.96,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 120,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Interview Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 749848321,
                doorPos = vector3(1852.92, 3686.40, 30.41),
                textPos = vector3(1852.12, 3685.87, 30.26),
                heading = 29.87,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Viewing Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 749848321,
                doorPos = vector3(1856.16, 3688.26, 30.41),
                textPos = vector3(1855.32, 3687.80, 30.26),
                heading = 29.87,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cells Entrance',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1927754726,
                doorPos = vector3(1859.69, 3686.64, 30.40),
                textPos = vector3(1859.25, 3687.60, 30.26),
                heading = 299.94,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1927754726,
                doorPos = vector3(1862.76, 3688.41, 30.40),
                textPos = vector3(1862.20, 3689.26, 30.26),
                heading = 299.75,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1927754726,
                doorPos = vector3(1860.98, 3691.64, 30.40),
                textPos = vector3(1860.40, 3692.56, 30.26),
                heading = 300.00,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell3',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1927754726,
                doorPos = vector3(1858.99, 3694.93, 30.40),
                textPos = vector3(1858.42, 3695.86, 30.26),
                heading = 300.00,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },                                                                       
        }
    },
    {
        location = 'Pillbox',
        centralPos = vector3(326.9283, -591.1274, 43.28398),
        distanceCheck = 50,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'Reception Entry',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(313.48, -595.46, 43.43),
                textPos = vector3(313.27, -596.01, 43.28),
                heading = 249.80,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Staff Room',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(309.13, -597.75, 43.43),
                textPos = vector3(308.62, -597.48, 43.28),
                heading = 160.17,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Closet',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(303.96, -572.56, 43.43),
                textPos = vector3(304.21, -571.86, 43.28),
                heading = 70.02,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Lab',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(307.12, -569.57, 43.43),
                textPos = vector3(307.77, -569.73, 43.28),
                heading = 340.00,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'MRI',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(336.16, -580.14, 43.43),
                textPos = vector3(336.70, -580.33, 43.28),
                heading = 339.88,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Diagnostics',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(340.78, -581.82, 43.43),
                textPos = vector3(341.36, -582.17, 43.28),
                heading = 340.00,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Xray',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(346.77, -584.00, 43.43),
                textPos = vector3(347.45, -584.25, 43.28),
                heading = 340.00,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Admin',
                jobs = {'police', 'ambulance'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 854291622,
                doorPos = vector3(339.01, -586.70, 43.43),
                textPos = vector3(339.61, -586.89, 43.28),
                heading = 340.00,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
        }
    },
    -- {
    --      location = 'PDM',
    --      centralPos = vector3(-42.31, -1098.81, 26.42),
    --      distanceCheck = 30,
    --      doors =
    --      {       -- doorModel Key (1 or 2) MUST match doorPos
    --          {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
    --             name = 'DoubleDoorSide',
    --              jobs = {'police'},
    --              multiModel = true,
    --              doubleDoor = true,
    --              doorModel = {[1] = 'v_ilev_csr_door_l', [2] = 'v_ilev_csr_door_r'},
    --              doorPos = {[1] = vector3(-59.89302, -1092.95200, 26.88362), [2] = vector3(-60.54582, -1094.74900, 26.88872)},
    --              textPos = vector3(-60.09, -1093.87, 26.67),
    --              heading1 = 250.0,
    --              heading2 = -110.0,
    --              isLocked = true,
    --              unlockDistance = 4.0,
    --              canPlyLockpick = true,
    --              autoLock = true,
    --              relock = false,
    --              autoLockTimer = 120,
    --              autoLockCooldown = 0,
    --              lockAtNight = false
    --          }
    --      }
    -- }
    {
        location = 'Prison Visitor Centre',
        centralPos = vector3(1828.72, 2593.13, 45.95),
        distanceCheck = 14,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            -- {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
            --     name = 'Primary Visitor Door',
            --     jobs = {'police'},
            --     multiModel = false,
            --     doubleDoor = false,
            --     doorModel = -1033001619,
            --     doorPos = vector3(1845, 2585.24, 46.09929),
            --     textPos = vector3(1845, 2585.24, 46.09929),
            --     heading = 89.923,
            --     isLocked = true,
            --     unlockDistance = 1.0,
            --     canPlyLockpick = false,
            --     autoLock = true,
            --     relock = true,
            --     autoLockTimer = 180,
            --     autoLockCooldown = 0,
            --     lockAtNight = false
            -- },
            {
                name = 'Second Visitor Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1837.697, 2585.24, 46.09929),
                textPos = vector3(1837.69, 2586.31, 45.95),
                heading = 89.983,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Primary Secuirty Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1827.726, 2584.6, 46.09929),
                textPos = vector3(1828.79, 2584.55, 45.95),
                heading = 359.769,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Visitor Corridor Door 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1827.365, 2587.547, 46.09929),
                textPos = vector3(1828.38, 2587.52, 45.95),
                heading = 359.743,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Visitor Corridor Door 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1819.129, 2593.64, 46.09929),
                textPos = vector3(1819.10, 2594.64, 45.95),
                heading = 89.591,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Visitor Centre Backdoor',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1826.466, 2585.271, 46.09929),
                textPos = vector3(1826.48, 2586.29, 45.95),
                heading = 89.809,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Visitor Reception',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1837.714, 2595.185, 46.099),
                textPos = vector3(1837.714, 2594.585, 46.099),
                heading = 270.292,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Visitor Reception Back Office',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1033001619,
                doorPos = vector3(1834.002, 2591.111, 46.09929),
                textPos = vector3(1834.002, 2591.111, 46.09929),
                heading = 89.688,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
        }
    },
    {
        location = 'Prison Block 2A',
        centralPos = vector3(1780.30, 2588.07, 45.80),
        distanceCheck = 22,
        doors =
        {       -- doorModel Key (1 or 2) MUST match doorPos
            {   -- if the left door is key 1 for doorModel, then the left doors position MUST be key 1 for doorPos
                name = 'Outside Corridor Gate 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1156020871,
                doorPos = vector3(1797.761, 2596.56, 46.38731),
                textPos = vector3(1796.019, 2596.589, 46.38366),
                heading = 180.000,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Outside Corridor Gate 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = -1156020871,
                doorPos = vector3(1798.09, 2591.687, 46.41784),
                textPos = vector3(1798.09, 2591.687, 46.41784),
                heading = 180.000,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Side Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 262839150,
                doorPos = vector3(1786.384, 2600.229, 46.08917),
                textPos = vector3(1785.26, 2600.22, 45.80),
                heading = 359.999,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Pantry Door 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1783.89, 2599.207, 45.97709),
                textPos = vector3(1783.88, 2598.06, 45.80),
                heading = 90.026,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Pantry Door 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1782.371, 2595.814, 45.97295),
                textPos = vector3(1781.34, 2595.77, 45.80),
                heading = 0.122,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Kitchen Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1774.917, 2593.757, 45.97295),
                textPos = vector3(1774.95, 2592.73, 45.80),
                heading = 89.817,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Main Block Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 430324891,
                doorPos = vector3(1784.608, 2590.46, 44.79552),
                textPos = vector3(1786.7, 2589.53, 45.49),
                heading = 159.914,
                isLocked = false,
                isGate = true,                
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Boilder Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1771.568, 2571.673, 50.72936),
                textPos = vector3(1771.57, 2570.66, 50.74),
                heading = 90.130,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Control Room',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1780.352, 2596.023, 50.839),
                textPos = vector3(1779.36, 2595.94, 50.81),
                heading = 1.448,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 `Visitor Stairs',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1787.711, 2606, 50.73208),
                textPos = vector3(1787.71, 2607.08, 50.55),
                heading = 269.826,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'A2 Visitor Back Door',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1787.711, 2606, 50.73208),
                textPos = vector3(1759.81, 2615.7, 45.56),
                heading = 269.826,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
        }
    },
    {
        location = 'Med Centre',
        centralPos = vector3(1785.57, 2556.93, 45.80),
        distanceCheck = 12,
        doors =
        {
            {
                name = 'Med Door 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1785.977, 2566.896, 45.98976),
                textPos = vector3(1784.91, 2566.91, 45.80),
                heading = 2.41,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Med Exit 1',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1645000677,
                doorPos = vector3(1776.125, 2551.352, 46.0925),
                textPos = vector3(1776.14, 2552.41, 46.11),
                heading = 269.838,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Med Exit 2',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 262839150,
                doorPos = vector3(1791.682, 2551.343, 46.09217),
                textPos = vector3(1791.62, 2552.34, 45.80),
                heading = 269.952,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Armory',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1784.653, 2550.299, 45.98037),
                textPos = vector3(1785.72, 2550.31, 45.80),
                heading = 179.866,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Office',
                jobs = {'police'},
                multiModel = false,
                doubleDoor = false,
                doorModel = 1028191914,
                doorPos = vector3(1786.27, 2551.77, 49.75),
                textPos = vector3(1786.29, 2550.71, 49.58),
                heading = 90.205,
                isLocked = true,
                unlockDistance = 1.5,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 180,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Double Doors Office',
                jobs = {'police'},
                doorModel = 1028191914,
                doubleDoor = true,
                doorPos = {[1] = vector3(1781.805, 2550.77, 49.764), [2] = vector3(1781.756, 2553.373, 49.754)},
                textPos = vector3(1781.81, 2552.07, 49.58),
                heading1 = 269.47,
                heading2 = 90.146,
                isLocked = true,
                unlockDistance = 2.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 120,
                autoLockCooldown = 0,
                lockAtNight = false
            },            

        }
    },
	{
        location = 'Paleto PD',  
        centralPos = vector3(-444.568, 6005.987, 31.7163),  
        distanceCheck = 40,  -- Distance used to grab all the doors in the area. MUST be large enough to cover all the doors for that building/area
        doors =
        {
            {
                name = 'Side Front Double',  -- Just used to identify the door
                jobs = {'police'},
                doorModel = 964838196,
                doubleDoor = true,
                doorPos = {[1] = vector3(-442.8215, 6010.931, 31.86633), [2] = vector3(-440.9807, 6012.771, 31.86633)},
                textPos = vector3(-441.8746, 6011.936, 31.71636),
                heading1 = 224.953,  -- When closed
                heading2 = 45.322,
                isLocked = true,  -- Default lock status
                unlockDistance = 1.5,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = false,  -- Whether the door can be lockpicked
                autoLock = true,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
            {
                name = 'Front Double',  -- Just used to identify the door
                jobs = {'police'},
				multiModel = true,
                doubleDoor = true,
                doorModel = {[1] = 245182344, [2] = -681066206},
                doorPos = {[1] = vector3(-447.7092, 6006.717, 31.80887), [2] = vector3(-449.55, 6008.558, 31.800887)},
                textPos = vector3(-448.728, 6007.674, 31.71633),
                heading1 = 315.0,  -- When closed
                heading2 = 135.0,
                isLocked = true,  -- Default lock status
                unlockDistance = 1.5,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = false,  -- Whether the door can be lockpicked
                autoLock = true,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
            {
                name = 'Interview Room',
                jobs = {'police'},
                doorModel = -519068795,
                doubleDoor = false,
                doorPos = vector3(-454.536, 6011.258, 31.86982),
                textPos = vector3(-453.8737, 6011.368, 31.71636),
                heading = 10.009,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            }, 
            {
                name = 'Viewing Room',
                jobs = {'police'},
                doorModel = -2023754432,
                doubleDoor = false,
                doorPos = vector3(-449.7946, 6015.448, 31.86633),
                textPos = vector3(-450.2769, 6015.736, 31.71634),
                heading = 135.504,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },                
            {
                name = 'Cell 1',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-431.1921, 5999.742, 31.87312),
                textPos = vector3(-431.5249, 6000.319, 31.71621),
                heading = 315.515,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },            
            {
                name = 'Cell 2',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-428.0646, 5996.672, 31.87312),
                textPos = vector3(-428.4395, 5997.172, 31.71621),
                heading = 315.515,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = true,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Cell Gate',
                jobs = {'police'},
                doorModel = 631614199,
                doubleDoor = false,
                doorPos = vector3(-432.1754, 5992.122, 31.87312),
                textPos = vector3(-432.613, 5992.531, 31.7162),
                heading = 315.272,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Evidence Gate',
                jobs = {'police'},
                doorModel = -1011692606,
                doubleDoor = false,
                doorPos = vector3(-437.6144, 5992.819, 31.936),
                textPos = vector3(-436.9706, 5992.238, 31.7162),
                heading = 314.670,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Back Door 1',
                jobs = {'police'},
                doorModel = 452874391,
                doubleDoor = false,
                doorPos = vector3(-447.2263, 6002.329, 31.83943),
                textPos = vector3(-446.623, 6001.917, 31.7162),
                heading = 134.837,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
            {
                name = 'Back Door 2',
                jobs = {'police'},
                doorModel = 452874391,
                doubleDoor = false,
                doorPos = vector3(-450.9787, 6006.075, 31.99417),
                textPos = vector3(-451.3818, 6006.563, 31.83926),
                heading = 315.336,
                isLocked = true,
                unlockDistance = 1.0,
                canPlyLockpick = false,
                autoLock = false,
                relock = false,
                autoLockTimer = 5,
                autoLockCooldown = 0,
                lockAtNight = false
            },
        }
    },
    {
        location = 'Humane Labs',  
        centralPos = vector3(3593.9548, 3689.0615, 28.821378),  
        distanceCheck = 100,  -- Distance used to grab all the doors in the area. MUST be large enough to cover all the doors for that building/area
        doors =
        {
            {
                name = 'Rear Slide Exit1',  -- Just used to identify the door
                jobs = {'police'},
                doorModel = -1081024910,
                doubleDoor = false,
                doorPos = vector3(3627.713, 3746.716, 27.68705),
                textPos = vector3(3627.713, 3746.716, 28.68705),
                heading = 325.0,
                isLocked = true,  -- Default lock status
                isGate = true,
                unlockDistance = 2.5,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = false,  -- Whether the door can be lockpicked
                autoLock = true,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
            {
                name = 'Rear Slide Exit2',  -- Just used to identify the door
                jobs = {'police'},
                doorModel = -1081024910,
                doubleDoor = false,
                doorPos = vector3(3620.84, 3751.524, 27.69208),
                textPos = vector3(3620.84, 3751.524, 28.69208),
                heading = 325.0,
                isLocked = true,  -- Default lock status
                isGate = true,
                unlockDistance = 2.5,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = false,  -- Whether the door can be lockpicked
                autoLock = true,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
            {
                name = 'Lower Exit',  -- Just used to identify the door
                jobs = {'police'},
                doorModel = 19193616,
                doubleDoor = false,
                doorPos = vector3(3526.021, 3702.243, 21.34196),
                textPos = vector3(3526.021, 3702.243, 21.34196),
                heading = 169.0,
                isLocked = true,  -- Default lock status
                isGate = false,
                unlockDistance = 1.5,  -- Distance that both text is drawn, and how far away the player can be to unlock the door
                canPlyLockpick = true,  -- Whether the door can be lockpicked
                autoLock = false,  -- Whether the door will autolock if it's lockpicked
                relock = false,  -- Used to signal that the door was lockpicked and will autolock again. This is so doors unlocked normally won't autolock
                autoLockTimer = 5,  -- Time till the door autolocks in seconds
                autoLockCooldown = 0,  -- Autolock counter
                lockAtNight = false  -- Whether the door will lock at night or not
            },
        }
    },
}